#config/doctrine/Entity.Resourceb.dcm.yml
Entity\Resourceb:
    type: entity
    table: resourceb
    fields:
        idrsc :
            type: bigint
            id: true
            generator:
                strategy: AUTO
        Id:
            type: bigint
        ResourceId:
            type: bigint
        ResourceName:
            type: text
        CTRRuleta_c:
            type: text
        Username:
            type: text
        CTROrdenRuleta_c:
            type: text
        EmailAddress:
            type: text
    lifecycleCallbacks: {  }